from pydantic import BaseModel, Field
from typing import List, Literal
from datetime import datetime
import uuid

class InsightCard(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    category: Literal["portfolio", "market", "watchlist"] = Field(..., description="Category of the insight.")
    title: str = Field(..., min_length=1, max_length=200, description="Short, descriptive title for the insight.")
    content: str = Field(..., min_length=1, max_length=2000, description="Neutral, descriptive summary. No financial advice.")
    severity: Literal["positive", "negative", "neutral", "warning"] = Field(default="neutral", description="Severity level of the insight.")

class InsightResponse(BaseModel):
    id: str
    created_at: datetime
    model_used: str = "deterministic"
    quality_score: float = Field(default=0.0, ge=0.0, le=1.0)
    cards: List[InsightCard] = Field(default_factory=list, max_length=10)
    disclaimer: str = "This summary is generated by AI for informational purposes only and does not constitute financial advice."

class InsightGenerateRequest(BaseModel):
    include_portfolio: bool = True
    include_watchlist: bool = True
