export type TabParamList = {
  Dashboard: undefined;
  Markets: undefined;
  Convert: undefined;
  Portfolio: undefined;
  Profile: undefined;
};

export type AppStackParamList = {
  Tabs: undefined;
  AddTransaction: undefined;
  AssetDetail: { symbol?: string } | undefined;
  Alerts: undefined;
  AlertHistory: undefined;
  Watchlist: undefined;
  Insights: undefined;
  EditProfile: undefined;
  CompareAssets: undefined;
  MarketNews: undefined;
  FifoSummary: undefined;
  StrategyHub: undefined;
  Academy: undefined;
  AcademyArticle: { slug: string; locale?: string } | undefined;
  WeeklyRecap: undefined;
  MonthlyWrapped: undefined;
  SharedWatchlist: { token: string } | undefined;
  TwoFactor: undefined;
  IntelligenceHub: undefined;
  PortfolioPowersHub: undefined;
  PortfolioDenomination: undefined;
  PortfolioRebalancer: undefined;
  PortfolioDcaSimulator: undefined;
  PaperOrders: undefined;
  PortfolioTaxLots: undefined;
  PortfolioMultiGoals: undefined;
  PortfolioShared: undefined;
  PortfolioStressTest: undefined;
  SocialHub: undefined;
  ShareCardStudio: { symbol?: string } | undefined;
  CommunityLists: undefined;
  CommunityListDetail: { slug: string };
  CopyStrategy: undefined;
  Leaderboard: undefined;
  Referral: undefined;
  LiveEvents: undefined;
  ProToolsHub: undefined;
  TechnicalAnalysis: { symbol?: string } | undefined;
  FormulaAlerts: undefined;
  SpreadDetector: { symbol?: string } | undefined;
  VolatilityCone: { symbol?: string } | undefined;
  PositionSlicing: { symbol?: string } | undefined;
  TaxReport: undefined;
  StrategyPlayground: undefined;
  Transparency: undefined;
};
